#!/bin/bash
set -e

# --- Configuration ---
CONDA_ENV_NAME="f5-tts"
PYTHON_VERSION="3.10"
MODEL_CACHE_DIR="models"
MODEL_DIR="${MODEL_CACHE_DIR}/F5TTS_v1_Base"

# Get the absolute path of the project directory
PROJECT_DIR=$(pwd)

# --- Helper Functions ---
print_info() {
    echo " "
    echo "======================================================================="
    echo "=> $1"
    echo "======================================================================="
    echo " "
}

# --- Main Script ---

# 1. Check for Conda
if ! command -v conda &> /dev/null; then
    echo "Error: Conda is not installed or not in your PATH. Please install Conda first."
    exit 1
fi

# 2. Create and Activate Conda Environment
print_info "Setting up Conda environment: ${CONDA_ENV_NAME}"
if ! conda env list | grep -q "${CONDA_ENV_NAME}"; then
    conda create -n "${CONDA_ENV_NAME}" python=${PYTHON_VERSION} -y
fi

# Activate the environment for the rest of the script
source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate "${CONDA_ENV_NAME}"

# 3. Install Dependencies
print_info "Installing dependencies..."
conda install -c conda-forge ffmpeg -y
pip install -r requirements.txt
pip install torch torchaudio --index-url https://download.pytorch.org/whl/cu118

# 4. Install F5-TTS
print_info "Installing F5-TTS engine..."
pip install f5-tts

# 5. Create .env file
print_info "Creating .env configuration file..."
mkdir -p ai_dubbing
ENV_FILE="ai_dubbing/.env"
if [ -f "$ENV_FILE" ]; then
    echo ".env file already exists. Updating F5-TTS configuration..."
    # Update existing .env file with MODEL_CACHE_DIR config
    if grep -q "MODEL_CACHE_DIR" "$ENV_FILE"; then
        sed -i "s|MODEL_CACHE_DIR=.*|MODEL_CACHE_DIR=${PROJECT_DIR}/${MODEL_CACHE_DIR}|" "$ENV_FILE"
    else
        echo "MODEL_CACHE_DIR=${PROJECT_DIR}/${MODEL_CACHE_DIR}" >> "$ENV_FILE"
    fi
else
    echo "# Auto-generated by install-f5-tts.sh" > "${ENV_FILE}"
    echo "MODEL_CACHE_DIR=${PROJECT_DIR}/${MODEL_CACHE_DIR}" >> "${ENV_FILE}"
    echo ".env file created at ${ENV_FILE}"
fi

# 6. Prepare model directory
print_info "Preparing model directory..."
mkdir -p "${MODEL_DIR}"
echo "F5-TTS models will be automatically downloaded on first use to ${MODEL_DIR}"

# 7. Installation Complete
print_info "F5-TTS installation completed successfully!"
echo " "
echo "To start the Web UI server with F5-TTS engine, run:"
echo "  conda activate ${CONDA_ENV_NAME}"
echo "  python server.py"
echo " "
echo "Make sure to set 'tts_engine = f5_tts' in your configuration."
echo "Models will be automatically downloaded on first use."
echo " "
