#!/bin/bash
set -e

# --- Configuration ---
CONDA_ENV_NAME="fish-speech"
PYTHON_VERSION="3.10"
FISH_SPEECH_REPO="https://github.com/fishaudio/fish-speech.git"
FISH_SPEECH_MODEL="fishaudio/openaudio-s1-mini"
DEPS_DIR="deps"
FISH_SPEECH_DIR="${DEPS_DIR}/fish-speech"
MODEL_CACHE_DIR="models"
MODEL_DIR="${MODEL_CACHE_DIR}/openaudio-s1-mini"

# Get the absolute path of the project directory
PROJECT_DIR=$(pwd)

# --- Helper Functions ---
print_info() {
    echo " "
    echo "======================================================================="
    echo "=> $1"
    echo "======================================================================="
    echo " "
}

# --- Main Script ---

# 1. Check for Conda
if ! command -v conda &> /dev/null; then
    echo "Error: Conda is not installed or not in your PATH. Please install Conda first."
    exit 1
fi

# 2. Create and Activate Conda Environment
print_info "Setting up Conda environment: ${CONDA_ENV_NAME}"
if ! conda env list | grep -q "${CONDA_ENV_NAME}"; then
    conda create -n "${CONDA_ENV_NAME}" python=${PYTHON_VERSION} -y
fi

# Activate the environment for the rest of the script
source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate "${CONDA_ENV_NAME}"

# 3. Install Dependencies
print_info "Installing dependencies..."
conda install -c conda-forge ffmpeg -y
pip install -r requirements.txt
pip install torch torchaudio --index-url https://download.pytorch.org/whl/cu118
pip install huggingface-hub

# 4. Clone and Install Fish Speech
print_info "Cloning and installing Fish Speech engine..."
mkdir -p "${DEPS_DIR}"
if [ -d "${FISH_SPEECH_DIR}" ]; then
    echo "Fish Speech directory already exists. Skipping clone."
else
    git clone "${FISH_SPEECH_REPO}" "${FISH_SPEECH_DIR}"
fi
cd "${FISH_SPEECH_DIR}"
pip install -e .
cd "${PROJECT_DIR}"

# 5. Create .env file
print_info "Creating .env configuration file..."
mkdir -p ai_dubbing
ENV_FILE="ai_dubbing/.env"
if [ -f "$ENV_FILE" ]; then
    echo ".env file already exists. Skipping creation."
else
    echo "# Auto-generated by run.sh" > "${ENV_FILE}"
    echo "MODEL_CACHE_DIR=${PROJECT_DIR}/${MODEL_CACHE_DIR}" >> "${ENV_FILE}"
    echo "FISH_SPEECH_DIR=${PROJECT_DIR}/${FISH_SPEECH_DIR}" >> "${ENV_FILE}"
    echo ".env file created at ${ENV_FILE}"
fi

# 6. Download Model
print_info "Downloading Fish Speech model..."
if [ -d "${MODEL_DIR}" ]; then
    echo "Model directory already exists. Skipping download."
else
    huggingface-cli download "${FISH_SPEECH_MODEL}" --local-dir "${MODEL_DIR}"
fi

# 7. Start Server
print_info "Starting the Web UI server..."
echo " "
echo "Server is running at http://127.0.0.1:8000"
echo "Press Ctrl+C to stop the server."
echo " "
python server.py
